/*
 * Lincheck
 *
 * Copyright (C) 2019 - 2026 JetBrains s.r.o.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed
 * with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package org.jetbrains.lincheck.trace.diff

sealed class DiffLine
data class UnchangedDiffLine(val leftIdx: Int, val rightIdx: Int): DiffLine()
data class RemovedDiffLine(val leftIdx: Int): DiffLine()
data class AddedDiffLine(val rightIdx: Int): DiffLine()

/**
 * Calculates the diff between two lists and return diff property.
 *
 * This implementation uses Myers' diff algorithm.
 *
 * Generated by Junie
 */
internal fun <T> diffLists(left: List<T>, leftSize: Int = left.size, right: List<T>, rightSize: Int = right.size, equals: (T, T) -> Boolean): List<DiffLine> {
    val n = leftSize // The size of the left list
    val m = rightSize // The size of the right list
    if (n == 0 && m == 0) return emptyList()

    val max = n + m // Maximum possible distance (edit script length)
    val v = IntArray(2 * max + 1) // DP table for the furthest reaching x-coordinates for each k-line
    val dpSnapshots = mutableListOf<IntArray>() // List of DP table snapshots for each d (distance)

    v[max + 1] = 0

    var x: Int // Current x-coordinate in the edit graph
    var y: Int // Current y-coordinate in the edit graph
    outer@ for (d in 0..max) { // d is the current distance (number of edits)
        val currentV = v.copyOf() // Snapshot of the current DP table
        dpSnapshots.add(currentV)
        for (k in -d..d step 2) { // k is the diagonal (k = x - y)
            val idx = k + max // Index in the v array
            x = if (k == -d || (k != d && v[idx - 1] < v[idx + 1])) {
                v[idx + 1]
            } else {
                v[idx - 1] + 1
            }
            y = x - k
            while (x < n && y < m && equals(left[x], right[y])) {
                x++
                y++
            }
            v[idx] = x
            if (x >= n && y >= m) {
                break@outer
            }
        }
    }

    val result = mutableListOf<DiffLine>() // The resulting list of diff lines (in reverse order)
    x = n
    y = m

    for (d in dpSnapshots.size - 1 downTo 0) { // d is the distance (number of edits)
        val k = x - y // Current diagonal
        val idx = k + max // Index in the v array
        val currentV = dpSnapshots[d] // DP table snapshot for the current distance d

        val prevK = if (k == -d || (k != d && currentV[idx - 1] < currentV[idx + 1])) {
            k + 1
        } else {
            k - 1
        }
        val prevX = currentV[prevK + max] // Previous x-coordinate
        val prevY = prevX - prevK // Previous y-coordinate

        while (x > prevX && y > prevY) {
            result.add(UnchangedDiffLine(x - 1, y - 1))
            x--
            y--
        }

        if (d > 0) {
            if (x > prevX) {
                result.add(RemovedDiffLine(x - 1))
                x--
            } else if (y > prevY) {
                result.add(AddedDiffLine(y - 1))
                y--
            }
        }
    }

    return result.reversed()
}
