/*
 * Lincheck
 *
 * Copyright (C) 2019 - 2023 JetBrains s.r.o.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed
 * with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.jetbrains.kotlinx.lincheck.execution;

import org.jetbrains.kotlinx.lincheck.Actor;
import org.jetbrains.kotlinx.lincheck.strategy.Strategy;

import java.util.*;
import java.util.stream.*;

import static org.jetbrains.kotlinx.lincheck.ReporterKt.appendExecutionScenario;

/**
 * This class represents an execution scenario, which
 * is generated by an {@link ExecutionGenerator} and then \
 * used by a {@link Strategy} which produces an {@link ExecutionResult}.
 */
public class ExecutionScenario {
    /**
     * The initial sequential part of the execution.
     * It helps to produce different initial states
     * before the parallel part.
     *
     * The initial execution part should contain only non-suspendable actors;
     * otherwise, the single initial execution thread will suspend with no chance to be resumed.
     */
    public final List<Actor> initExecution;
    /**
     * The parallel part of the execution, which is used
     * to find an interleaving with incorrect behaviour.
     */
    public final List<List<Actor>> parallelExecution;
    /**
     * The last sequential part is used to test that
     * the data structure is in some correct state.
     *
     * If this execution scenario contains suspendable actors, the post part should be empty;
     * if not, an actor could resume a previously suspended one from the parallel execution part.
     */
    public final List<Actor> postExecution;

    public ExecutionScenario(List<Actor> initExecution, List<List<Actor>> parallelExecution, List<Actor> postExecution) {
        this.initExecution = initExecution;
        this.parallelExecution = parallelExecution;
        this.postExecution = postExecution;
    }

    /**
     * Returns the number of threads used in the parallel part of this execution.
     */
    public int getThreads() {
        return parallelExecution.size();
    }

    /**
     * Returns `true` if there is at least one suspendable actor in the generated scenario
     */
    public boolean hasSuspendableActors() {
        return Stream.concat(parallelExecution.stream().flatMap(Collection::stream), postExecution.stream()).anyMatch(Actor::isSuspendable);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        appendExecutionScenario(sb, this);
        return sb.toString();
    }
}
