/*
 * Lincheck
 *
 * Copyright (C) 2019 - 2025 JetBrains s.r.o.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed
 * with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package org.jetbrains.kotlinx.lincheck.trace


internal fun SingleThreadedTable<TraceNode>.compressTrace() = this
    .compressSyntheticFieldAccess()
    .compressSuspendImpl()
    .compressDefaultPairs()
    .compressAccessPairs()
    .compressUserThreadRun()
    .compressThreadStart()
    .removeCoroutinesCoreSuffix()

/**
 * Compresses `receive$suspendImpl` calls.
 * 
 * These calls are part of suspend fun internals, but are not part of user code.
 * This function removes the `$suspendImpl` call and moves all its children to the parent.
 */
private fun SingleThreadedTable<TraceNode>.compressSuspendImpl() = compressNodes { node ->
    val singleChild = if (node.children.size == 1) node.children[0] else return@compressNodes node
    if (node !is CallNode || singleChild !is CallNode) return@compressNodes node
    if ("${node.tracePoint.methodName}\$suspendImpl" != singleChild.tracePoint.methodName) return@compressNodes node

    val newNode = node.copy()
    // trace grandchildren to children, inherit correct stackTraceElement, decrement depth
    singleChild.children.forEach {
        if (it.tracePoint is CodeLocationTracePoint) {
            (it.tracePoint as CodeLocationTracePoint).codeLocation = singleChild.tracePoint.codeLocation
        }
        it.decrementCallDepthOfTree()
        newNode.addChild(it)
    }
    newNode
}

/**
 * Compresses `fun$default(...)` calls.
 *
 * Kotlin functions with default values are represented as two nested calls in the stack trace.
 *
 * For example:
 *
 * ```
 * A.calLMe$default(A#1, 3, null, 2, null) at A.operation(A.kt:23)
 *   A.callMe(3, "Hey") at A.callMe$default(A.kt:27)
 * ```
 *
 * will be collapsed into:
 *
 * ```
 * A.callMe(3, "Hey") at A.operation(A.kt:23)
 * ```
 *
 */
private fun SingleThreadedTable<TraceNode>.compressDefaultPairs() = compressNodes { node ->
    val singleChild = if (node.children.size == 1) node.children[0] else return@compressNodes node
    if (node !is CallNode || singleChild !is CallNode) return@compressNodes node
    if (!haveSameOwner(node.tracePoint, singleChild.tracePoint) || !isDefaultPair(node.tracePoint.methodName, singleChild.tracePoint.methodName)) return@compressNodes node
    combineNodes(node, singleChild)
}

/**
 * Compresses `.access$` calls.
 *
 * The `.access$` methods are generated by the Kotlin compiler to access otherwise inaccessible members
 * (e.g., private) from lambdas, inner classes, etc.
 *
 * For example:
 *
 * ```
 * A.access$callMe() at A.operation(A.kt:N)
 *  A.callMe() at A.access$callMe(A.kt:N)
 * ```
 *
 * will be collapsed into:
 *
 * ```
 * A.callMe() at A.operation(A.kt:N)
 * ```
 *
 */
private fun SingleThreadedTable<TraceNode>.compressAccessPairs() = compressNodes { node ->
    val singleChild = if (node.children.size == 1) node.children[0] else return@compressNodes node
    if (node !is CallNode || singleChild !is CallNode) return@compressNodes node
    if (!haveSameOwner(node.tracePoint, singleChild.tracePoint) || !isAccessPair(node.tracePoint.methodName, singleChild.tracePoint.methodName)) return@compressNodes node
    combineNodes(node, singleChild)
}

/**
 * Combine trace node for `default` and `access` functions.
 * For more details check [isDefaultPair] and [isAccessPair].
 */
private fun combineNodes(parent: CallNode, child: CallNode): TraceNode {
    parent.tracePoint.methodName = child.tracePoint.methodName
    parent.tracePoint.parameters = child.tracePoint.parameters

    check(parent.tracePoint.returnedValue == child.tracePoint.returnedValue)
    check(parent.tracePoint.thrownException == child.tracePoint.thrownException)

    val newNode = parent.copy() 
    child.decrementCallDepthOfTree()
    child.children.forEach { newNode.addChild(it) }
    return newNode
}

/**
 * Remove `access$get` and `access$set`, which is used when a lambda argument accesses a private field for example.
 * This is different from `fun$access`, which is addressed in [compressDefaultAndAccessPairs].
 */
private fun SingleThreadedTable<TraceNode>.compressSyntheticFieldAccess() = compressNodes { node ->
    val singleChild = if (node.children.size == 1) node.children[0] else return@compressNodes node
    if (node !is CallNode || singleChild !is EventNode) return@compressNodes node
    if (!isSyntheticFieldAccess(node.tracePoint.methodName)) return@compressNodes node

    val point = singleChild.tracePoint
    if (point is ReadTracePoint) point.codeLocation = node.tracePoint.codeLocation
    if (point is WriteTracePoint) point.codeLocation = node.tracePoint.codeLocation

    singleChild.decrementCallDepthOfTree()
    singleChild
}

private fun SingleThreadedTable<TraceNode>.removeCoroutinesCoreSuffix() = compressNodes { node ->
    if (node is CallNode && node.tracePoint.methodName.endsWith("\$kotlinx_coroutines_core")) {
        node.tracePoint.methodName = node.tracePoint.methodName.removeSuffix("\$kotlinx_coroutines_core")
    }
    
    if (node.tracePoint is CodeLocationTracePoint && (node.tracePoint as CodeLocationTracePoint).stackTraceElement.methodName.endsWith("\$kotlinx_coroutines_core")) {
        val oldStackTraceElement = (node.tracePoint as CodeLocationTracePoint).stackTraceElement
        val newStackTraceElement = StackTraceElement(
            oldStackTraceElement.className,
            oldStackTraceElement.methodName.removeSuffix("\$kotlinx_coroutines_core"),
            oldStackTraceElement.fileName,
            oldStackTraceElement.lineNumber,
        )
        (node.tracePoint as CodeLocationTracePoint).stackTraceElement = newStackTraceElement
    }
    
    node
}

/**
 * Removes the two `invoke()` lines at the beginning of a user-defined thread trace.
 */
private fun SingleThreadedTable<TraceNode>.compressUserThreadRun() = compressNodes { node ->
    if (node !is CallNode || !node.tracePoint.isThreadStart ) return@compressNodes node
    val firstChild = if (node.children.size == 1) node.children[0] else return@compressNodes node
    val secondChild = if (firstChild.children.size == 1) firstChild.children[0] else return@compressNodes node

    // Test if we are dealing with a custom thread start
    if (firstChild !is CallNode || secondChild !is CallNode) return@compressNodes node
    if (!isUserThreadStart(firstChild.tracePoint, secondChild.tracePoint)) return@compressNodes node

    val newNode = node.copy()
    node.children.getOrNull(0)?.children?.getOrNull(0)?.children?.forEach {
        it.decrementCallDepthOfTree()
        it.decrementCallDepthOfTree()
        newNode.addChild(it)
    }
    newNode
}

/**
 * When `thread() { ... }` is called it is represented as
 * ```
 * thread creation line: Thread#2 at A.fun(location)
 *     Thread#2.start()
 * ```
 * this function gets rid of the second line.
 * But only if it has been created with `thread(start = true)`
 */
private fun SingleThreadedTable<TraceNode>.compressThreadStart() = compressNodes { node ->
    if (node !is CallNode || !node.tracePoint.isThreadCreation() ) return@compressNodes node
    val firstChild = if (node.children.size == 1) node.children[0] else return@compressNodes node
    val secondChild = if (firstChild.children.size == 1) firstChild.children[0] else return@compressNodes node
    if (secondChild !is EventNode || secondChild.tracePoint !is ThreadStartTracePoint) return@compressNodes node

    val newNode = node.copy()
    newNode.addChild(secondChild)
    newNode
}


private fun SingleThreadedTable<TraceNode>.compressNodes(compressionRule: (TraceNode) -> TraceNode) = map {
    it.map { it.compress(compressionRule) }
}

private fun TraceNode.compress(compressionRule: (TraceNode) -> TraceNode): TraceNode {
    val compressedNode = compressionRule(this)
    val newNode = compressedNode.copy()
    compressedNode.children.forEach { newNode.addChild(it.compress(compressionRule)) }
    return newNode
}

/**
 * Used in [compressDefaultPairs] and [compressAccessPairs]
 */
private fun haveSameOwner(currentPoint: MethodCallTracePoint, nextPoint: MethodCallTracePoint): Boolean =
    currentPoint.className == nextPoint.className

/**
 * Used in [compressDefaultPairs]
 */
private fun isDefaultPair(currentName: String, nextName: String): Boolean =
    currentName == "${nextName}\$default"

/**
 * Used in [compressAccessPairs]
 */
private fun isAccessPair(currentName: String, nextName: String): Boolean =
    currentName == "access$${nextName}"

private fun isSyntheticFieldAccess(methodName: String): Boolean =
    methodName.contains("access\$get") || methodName.contains("access\$set")

/**
 * Used to remove the two `invoke()` lines at the beginning of
 * a user-defined thread trace.
 */
private fun isUserThreadStart(currentTracePoint: MethodCallTracePoint, nextTracePoint: MethodCallTracePoint): Boolean =
    currentTracePoint.stackTraceElement.methodName == "run"
            && currentTracePoint.stackTraceElement.fileName == "Thread.kt"
            && currentTracePoint.methodName == "invoke"
            && nextTracePoint.methodName == "invoke"
