/*
 * Lincheck
 *
 * Copyright (C) 2019 - 2025 JetBrains s.r.o.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed
 * with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package org.jetbrains.trace.recorder.test

import java.nio.file.Path
import kotlin.io.path.writeText

abstract class AbstractJsonTraceRecorderIntegrationTest(
    override val projectPath: String,
) : AbstractTraceRecorderIntegrationTest() {
    override val formatArgs: Map<String, String> = mapOf("format" to "binary", "formatOption" to "stream")

    data class TestCase(
        val className: String,
        val methodName: String,
        val gradleCommand: String,
        val jvmArgs: List<String>,
        val checkRepresentation: Boolean,
    )

    open fun test(testCase: TestCase) = runGradleTest(
        testClassName = testCase.className,
        testMethodName = testCase.methodName,
        extraJvmArgs = testCase.jvmArgs,
        gradleCommands = listOf(testCase.gradleCommand),
        checkRepresentation = testCase.checkRepresentation,
    )

    companion object {
        fun getAllTestCases(resourcePath: String): Collection<TestCase> {
            val json = loadResourceText(resourcePath, this::class.java)
            val entries = parseJsonEntries(json)
            return entries.flatMap { (className, gradleCommand, methods, jvmArgs, checkRepresentation) ->
                methods.map { TestCase(className, it, gradleCommand, jvmArgs, checkRepresentation) }
            }
        }

        fun renderSingleTestCode(
            groupName: String,
            testCase: TestCase,
            abstractTestClass: String,
            timeoutMinutes: Long,
            useSimpleClassName: Boolean
        ): String {
            val formattedOriginalClassName = testCase.className
                .let { if (useSimpleClassName) it.substringAfterLast(".") else it.replace('.', '_') }
                .replace('$', '_')

            val generatedTestClassName =
                """${groupName}TraceRecorderIntegrationTest_${formattedOriginalClassName}_${testCase.methodName}"""
                    .let { if (it.contains(' ')) "`$it`" else it }

            fun String.toLiteral(): String {
                val dollarsCount = generateSequence("") { "$it$" }.takeWhile { it in this }.last().length
                val dollarPrefix = if (dollarsCount == 0) "" else "$".repeat(dollarsCount + 1)
                return "$dollarPrefix\"$this\""
            }

            return """
                @Category(ExtendedTraceRecorderTest::class)
                class $generatedTestClassName : $abstractTestClass() {
                    @Test(timeout = $timeoutMinutes * 60 * 1000L)
                    fun test() {
                        test(
                            TestCase(
                                className = ${testCase.className.toLiteral()},
                                methodName = ${testCase.methodName.toLiteral()},
                                jvmArgs = listOf(${testCase.jvmArgs.joinToString { it.toLiteral() }}),
                                gradleCommand = ${testCase.gradleCommand.toLiteral()},
                                checkRepresentation = ${testCase.checkRepresentation},
                            )
                        )
                    }
                }
                """.trimIndent()
        }

        fun renderAllTestsCode(
            groupName: String,
            resourcePath: String,
            abstractTestClass: String,
            packageName: String,
            customImports: List<String>,
            timeoutMinutes: Long,
        ): String {
            val testCases = getAllTestCases(resourcePath)

            val clashes = testCases
                .groupBy(
                    keySelector = { it.className.substringAfterLast(".") to it.methodName },
                    valueTransform = { it.className }
                )
                .filter { (_, cases) -> cases.size > 1 }
                .values.flatten()

            val beforeCustomImports = """
                @file:Suppress("ClassName")
                
                package $packageName
                
                import org.jetbrains.trace.recorder.test.*
                import org.junit.Test
                import org.junit.experimental.categories.Category
                """.trimIndent()

            val disclaimer = """
                /*
                  THIS FILE IS AUTOGENERATED!
                  DO NOT MODIFY!
                */
                """.trimIndent()

            val renderedTestCases = testCases.joinToString("\n\n") {
                renderSingleTestCode(groupName, it, abstractTestClass, timeoutMinutes, !clashes.contains(it.className))
            }

            return "$beforeCustomImports${customImports.joinToString("\n")}\n\n$disclaimer\n\n$renderedTestCases\n"
        }
    }
}

sealed class TestGenerator(
    val groupName: String,
    private val resourcePath: String,
    private val abstractTestClass: String,
    private val packageName: String,
    private val imports: List<String> = listOf(),
    private val timeoutMinutes: Long = 20,
) {
    fun generateString(): String = AbstractJsonTraceRecorderIntegrationTest.renderAllTestsCode(
        groupName, resourcePath, abstractTestClass, packageName, imports, timeoutMinutes
    )

    fun generateFile(path: Path) {
        path.writeText(generateString())
    }
}
