/*
 * Lincheck
 *
 * Copyright (C) 2019 - 2026 JetBrains s.r.o.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed
 * with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package org.jetbrains.lincheck.trace.tree

import org.jetbrains.lincheck.descriptors.toType
import org.jetbrains.lincheck.trace.TRArrayTracePoint
import org.jetbrains.lincheck.trace.TRFieldTracePoint
import org.jetbrains.lincheck.trace.TRLocalVariableTracePoint
import org.jetbrains.lincheck.trace.TRLoopIterationTracePoint
import org.jetbrains.lincheck.trace.TRLoopTracePoint
import org.jetbrains.lincheck.trace.TRMethodCallTracePoint
import org.jetbrains.lincheck.trace.TRReadFieldTracePoint
import org.jetbrains.lincheck.trace.TRTracePoint
import org.jetbrains.lincheck.trace.TRWriteFieldTracePoint
import org.jetbrains.lincheck.trace.TraceContext
import org.jetbrains.lincheck.trace.className
import org.jetbrains.lincheck.trace.isAccessPair
import org.jetbrains.lincheck.trace.isAutoGeneratedFieldGetterName
import org.jetbrains.lincheck.trace.isAutoGeneratedFieldSetterName
import org.jetbrains.lincheck.trace.isDefaultPair
import org.jetbrains.lincheck.trace.isSyntheticFieldAccess
import org.jetbrains.lincheck.trace.isSyntheticGetFieldAccess
import org.jetbrains.lincheck.util.tree.TreeRewriteRule
import org.jetbrains.lincheck.util.tree.Tree
import org.jetbrains.lincheck.util.tree.node
import org.jetbrains.lincheck.util.tree.rewrite

/*
 * Every rule reads only tree-level children (never the tracepoint's internal state),
 * so a rule stacked on top of another sees the already-rewritten tree.
 * Synthesized trace points are new objects wrapped into detached nodes built with the [node] DSL,
 * adopting existing subtrees as lazy copies; the source tree is never mutated.
 */

/**
 * A read-only view of this trace tree with all `CompressingPostprocessor` steps applied as rewrite rules.
 *
 * The rules are merged into two rewritten tree views (see [rewrite]) instead of one view per rule
 * to keep the number of view wrappers (and their caches) small.
 * Within a view, a rule peeking into a candidate's children sees the source tree,
 * which matches the original postprocessor's raw `events`-based checks for every rule here —
 * except [removeEmptyLoopOrUpdateIterationsRule],
 * which must observe the empty-iteration removal done by [removeLastEmptyLoopIterationRule]
 * and therefore forms the second view.
 */
// TODO: maybe merging loop postprocessing is possible to get rid of the double tree structure
fun Tree<TRTracePoint>.compressedView(context: TraceContext): Tree<TRTracePoint> =
    rewrite(
        listOf(
            compressDefaultPairsRule(context),
            compressAccessPairsRule(context),
            compressSyntheticFieldAccessRule(context),
            compressAutoGeneratedFieldAccessRule(context),
            removeCoverageInstructionsRule(),
            removeLastEmptyLoopIterationRule(),
        )
    )
    .rewrite(removeEmptyLoopOrUpdateIterationsRule(context))

/**
 * Compresses `fun$default(...)` call pairs produced by Kotlin functions with default parameter values.
 *
 * ```
 * A.callMe$default(A#1, 3, null, 2, null) at A.operation(A.kt:23)
 *   A.callMe(3, "Hey") at A.callMe$default(A.kt:27)
 * ```
 * collapses into
 * ```
 * A.callMe(3, "Hey") at A.operation(A.kt:23)
 * ```
 */
fun compressDefaultPairsRule(context: TraceContext): TreeRewriteRule<TRTracePoint> =
    combineCallPairsRule(context, ::isDefaultPair)

/**
 * Compresses `access$fun` call pairs generated by the Kotlin compiler
 * to reach otherwise inaccessible members from lambdas, inner classes, etc.
 *
 * ```
 * A.access$callMe() at A.operation(A.kt:N)
 *   A.callMe() at A.access$callMe(A.kt:N)
 * ```
 * collapses into
 * ```
 * A.callMe() at A.operation(A.kt:N)
 * ```
 */
fun compressAccessPairsRule(context: TraceContext): TreeRewriteRule<TRTracePoint> =
    combineCallPairsRule(context, ::isAccessPair)

private fun combineCallPairsRule(
    context: TraceContext,
    isPair: (parentName: String, childName: String) -> Boolean,
): TreeRewriteRule<TRTracePoint> = TreeRewriteRule { node ->
    val call = node.data as? TRMethodCallTracePoint ?: return@TreeRewriteRule node
    val nodeChildren = node.children
    if (nodeChildren.size != 1) return@TreeRewriteRule node
    val innerNode = nodeChildren[0]
    val innerCall = innerNode.data as? TRMethodCallTracePoint ?: return@TreeRewriteRule node
    if (call.className != innerCall.className || !isPair(call.methodName, innerCall.methodName)) return@TreeRewriteRule node
    node<TRTracePoint>(combineCallTracePoints(context, call, innerCall)) {
        innerNode.children.forEach { lazyNode(it) }
    }
}

private fun combineCallTracePoints(
    context: TraceContext,
    parent: TRMethodCallTracePoint,
    child: TRMethodCallTracePoint,
): TRMethodCallTracePoint {
    val combined = TRMethodCallTracePoint(
        context,
        child.threadId,
        // Code location is taken from the parent trace point and not from the child
        // because in the trace sidebar of the plugin for proper clicking to work
        // the code location reference must be the same as for the parent
        parent.codeLocationId,
        child.methodId,
        child.obj,
        child.parameters,
        child.flags,
        child.eventId,
    )
    combined.copyDiffStatus(child)
    combined.result = child.result
    combined.exceptionClassName = child.exceptionClassName
    return combined
}

/**
 * Compresses synthetic field access methods (`access$get...` / `access$set...`)
 * generated when a lambda or inner class accesses a private field.
 *
 * ```
 * A.access$get_field(A#1) at A.operation(A.kt:N)
 *   this ➜ A#1 at A.access$get_field(A.kt:N)
 *   A#1.field ➜ value at A.access$get_field(A.kt:N)
 * ```
 * collapses into
 * ```
 * A#1.field ➜ value at A.operation(A.kt:N)
 * ```
 * (the `set` version has three children and collapses into the field write).
 */
fun compressSyntheticFieldAccessRule(context: TraceContext): TreeRewriteRule<TRTracePoint> =
    TreeRewriteRule { node ->
        val call = node.data as? TRMethodCallTracePoint ?: return@TreeRewriteRule node
        if (!isSyntheticFieldAccess(call.methodName)) return@TreeRewriteRule node
        val nodeChildren = node.children
        // get and set method versions have different number of children (2 and 3, correspondingly);
        // the actual access is stored at the last position
        if (nodeChildren.size != 2 && nodeChildren.size != 3) return@TreeRewriteRule node
        val accessIndex = if (isSyntheticGetFieldAccess(call.methodName)) 1 else 2
        val newPoint = when (val access = nodeChildren.getOrNull(accessIndex)?.data) {
            is TRReadFieldTracePoint -> TRReadFieldTracePoint(
                context, access.threadId, call.codeLocationId, access.fieldId,
                access.obj, access.value, access.eventId,
            )
            is TRWriteFieldTracePoint -> TRWriteFieldTracePoint(
                context, access.threadId, call.codeLocationId, access.fieldId,
                access.obj, access.value, access.eventId,
            )
            else -> return@TreeRewriteRule node
        }
        newPoint.copyDiffStatus(call)
        node<TRTracePoint>(newPoint)
    }

/**
 * Compresses calls to auto-generated field getters and setters (`getField` / `setField`).
 *
 * ```
 * A.getFieldName() at A.operation(A.kt:N)
 *   A.fieldName ➜ value at A.getFieldName(A.kt:K)
 * ```
 * collapses into
 * ```
 * A.fieldName ➜ value at A.operation(A.kt:N)
 * ```
 * (the setter has an extra `<set-?>` parameter child and collapses into the field write).
 *
 * Custom getters/setters are kept: the getter must match the field's signature,
 * and the setter is recognized by its `<set-?>` parameter, which cannot appear in user code.
 */
fun compressAutoGeneratedFieldAccessRule(context: TraceContext): TreeRewriteRule<TRTracePoint> =
    TreeRewriteRule { node ->
        val call = node.data as? TRMethodCallTracePoint ?: return@TreeRewriteRule node
        val nodeChildren = node.children
        when (nodeChildren.size) {
            1 -> {
                val read = nodeChildren[0].data as? TRReadFieldTracePoint ?: return@TreeRewriteRule node
                val isAutoGeneratedGetter =
                    call.className == read.className &&
                    call.parameters.isEmpty() &&
                    call.methodDescriptor.returnType == read.value.className?.toType() &&
                    isAutoGeneratedFieldGetterName(call.methodName, read.name)
                if (!isAutoGeneratedGetter) return@TreeRewriteRule node
                val newPoint = TRReadFieldTracePoint(
                    context, read.threadId, call.codeLocationId, read.fieldId,
                    read.obj, read.value, read.eventId,
                )
                newPoint.copyDiffStatus(call)
                node<TRTracePoint>(newPoint)
            }
            2 -> {
                val param = nodeChildren[0].data as? TRLocalVariableTracePoint ?: return@TreeRewriteRule node
                val write = nodeChildren[1].data as? TRWriteFieldTracePoint ?: return@TreeRewriteRule node
                val isAutoGeneratedSetter =
                    param.name == "<set-?>" &&
                    call.className == write.className &&
                    isAutoGeneratedFieldSetterName(call.methodName, write.name)
                if (!isAutoGeneratedSetter) return@TreeRewriteRule node
                val newPoint = TRWriteFieldTracePoint(
                    context, write.threadId, call.codeLocationId, write.fieldId,
                    write.obj, write.value, write.eventId,
                )
                newPoint.copyDiffStatus(call)
                node<TRTracePoint>(newPoint)
            }
            else -> node
        }
    }

/**
 * Removes accesses to coverage instrumentation inserted by the intellij coverage agent (or kover plugin):
 * array, local variable, and (static) field accesses to `__$coverage_local$__` / `__$hits$__` /
 * `__$traceMask$__` / `__$classData$__`, together with their subtrees.
 */
fun removeCoverageInstructionsRule(): TreeRewriteRule<TRTracePoint> =
    TreeRewriteRule { node ->
        node.takeUnless { it.data.isCoverageInstruction() }
    }

private fun TRTracePoint.isCoverageInstruction(): Boolean = when (this) {
    is TRArrayTracePoint -> COVERAGE_ARRAY_NAMES.any { accessPath?.toString()?.contains(it) == true }
    is TRLocalVariableTracePoint -> name in COVERAGE_LOCAL_VAR_NAMES
    is TRFieldTracePoint -> name in COVERAGE_FIELD_NAMES
    else -> false
}

/**
 * Drops loop iterations that have no children.
 *
 * The CFG loop detection only produces empty iterations as the last one in a loop,
 * so this removes at most the trailing iteration of each loop.
 * The loop's iteration count is fixed up by [removeEmptyLoopOrUpdateIterationsRule],
 * which must be stacked in a view *above* this rule to observe the removal.
 */
fun removeLastEmptyLoopIterationRule(): TreeRewriteRule<TRTracePoint> =
    TreeRewriteRule { node ->
        node.takeUnless { it.data is TRLoopIterationTracePoint && it.children.isEmpty() }
    }

/**
 * Drops loops left without iterations and fixes up the `iterations` count
 * of loops whose empty trailing iteration was removed.
 *
 * Works in cooperation with [removeLastEmptyLoopIterationRule],
 * which must be stacked in a view *below* this rule
 * (a rule sees only the views beneath it, so within one view the removal would be invisible).
 */
fun removeEmptyLoopOrUpdateIterationsRule(context: TraceContext): TreeRewriteRule<TRTracePoint> =
    TreeRewriteRule { node ->
        val loop = node.data as? TRLoopTracePoint ?: return@TreeRewriteRule node
        val iterationNodes = node.children
        when {
            iterationNodes.isEmpty() -> null
            iterationNodes.size < loop.iterations -> {
                val newLoop = TRLoopTracePoint(
                    context, loop.threadId, loop.codeLocationId, loop.loopId,
                    loop.eventId, iterationNodes.size,
                )
                newLoop.copyDiffStatus(loop)
                node<TRTracePoint>(newLoop) {
                    iterationNodes.forEach { lazyNode(it) }
                }
            }
            else -> node
        }
    }

private val COVERAGE_LOCAL_VAR_NAMES = setOf("__\$coverage_local\$__", "__\$hits\$__" /* might be loaded via LDC */)
private val COVERAGE_FIELD_NAMES = setOf("__\$hits\$__", "__\$traceMask\$__", "__\$classData\$__")
private val COVERAGE_ARRAY_NAMES = COVERAGE_LOCAL_VAR_NAMES + COVERAGE_FIELD_NAMES
